language: node_js
node_js:
 - "8"
before_install:
 - "cd $TRAVIS_BUILD_DIR/game/hud && npm install"
 - "cd $TRAVIS_BUILD_DIR/library && npm install"
 - "cd $TRAVIS_BUILD_DIR/patcher && npm install"
script:
 - "cd $TRAVIS_BUILD_DIR/game/hud && npm start build && npm start test"
 - "cd $TRAVIS_BUILD_DIR/library && npm start build && npm start test"
 - "cd $TRAVIS_BUILD_DIR/patcher && npm start build"
