language: node_js
node_js:
 - "10"
cache:
  yarn: true
install:
 - "yarn"
 - "cd $TRAVIS_BUILD_DIR/library && yarn && yarn link"
 - "cd $TRAVIS_BUILD_DIR/game/hud && yarn && yarn link @csegames/camelot-unchained"
 - "cd $TRAVIS_BUILD_DIR/patcher && yarn && yarn link @csegames/camelot-unchained"
script:
 - "cd $TRAVIS_BUILD_DIR/library && yarn start build"
 - "cd $TRAVIS_BUILD_DIR/game/hud && yarn start build"
 - "cd $TRAVIS_BUILD_DIR/patcher && yarn start build"
notifications:
  email:
    - code@citystateentertainment.com
