language: node_js
node_js:
  - "7"
cache:
  yarn: true
install:
  - "yarn"
  - "cd $TRAVIS_BUILD_DIR/game/hud && yarn"
  - "cd $TRAVIS_BUILD_DIR/library && yarn"
  - "cd $TRAVIS_BUILD_DIR/patcher && yarn"
script:
  - "cd $TRAVIS_BUILD_DIR/game/hud && yarn start build && yarn start test"
  - "cd $TRAVIS_BUILD_DIR/library && yarn start build && yarn start test"
  - "cd $TRAVIS_BUILD_DIR/patcher && yarn start build"
