import { CSEChat } from './CSEChat';
import Config from './Config';
import EventEmitter from './EventEmitter';
import RoomId from '../components/RoomId';
declare class ChatClient {
    chat: CSEChat;
    connected: boolean;
    updated: number;
    errorListener: any;
    config: Config;
    emitter: EventEmitter;
    on(topic: string, handler: (data?: any) => void): any;
    off(id: any): void;
    connectWithToken(accessToken: string, nick?: string, rooms?: RoomId[]): void;
    connect(username: string | (() => string), password: string | (() => string), nick?: string, rooms?: RoomId[]): void;
    disconnect(): void;
    reconnect(rooms: RoomId[]): void;
    getNick(): string;
    getStoredRooms(): RoomId[];
    removeFromStoredRooms(room: string): void;
    addToStoredRooms(room: RoomId): void;
    setStoredRooms(rooms: RoomId[]): void;
    sendMessageToRoom(message: string, roomName: string): void;
    sendMessageToUser(message: string, userName: string): void;
    joinRoom(roomId: RoomId): void;
    leaveRoom(roomName: string): void;
    getRooms(): void;
    private _connect;
    private _online;
    private _onerror;
    private _initializeEvents;
    private _disconnect;
    private _fire;
    private internalConnect;
    private internalOnline;
    private internalOnError;
    private internalInitEvents;
    private internalDisconnect;
    private internalFire;
}
export default ChatClient;
