"use strict";
/**
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

Object.defineProperty(exports, "__esModule", { value: true });
var dxKeyCodes;
(function (dxKeyCodes) {
    dxKeyCodes[dxKeyCodes["ESCAPE"] = 1] = "ESCAPE";
    dxKeyCodes[dxKeyCodes[" 1 "] = 2] = " 1 ";
    dxKeyCodes[dxKeyCodes[" 2 "] = 3] = " 2 ";
    dxKeyCodes[dxKeyCodes[" 3 "] = 4] = " 3 ";
    dxKeyCodes[dxKeyCodes[" 4 "] = 5] = " 4 ";
    dxKeyCodes[dxKeyCodes[" 5 "] = 6] = " 5 ";
    dxKeyCodes[dxKeyCodes[" 6 "] = 7] = " 6 ";
    dxKeyCodes[dxKeyCodes[" 7 "] = 8] = " 7 ";
    dxKeyCodes[dxKeyCodes[" 8 "] = 9] = " 8 ";
    dxKeyCodes[dxKeyCodes[" 9 "] = 10] = " 9 ";
    dxKeyCodes[dxKeyCodes[" 0 "] = 11] = " 0 ";
    dxKeyCodes[dxKeyCodes["-"] = 12] = "-";
    dxKeyCodes[dxKeyCodes["="] = 13] = "=";
    dxKeyCodes[dxKeyCodes["BACKSPACE"] = 14] = "BACKSPACE";
    dxKeyCodes[dxKeyCodes["TAB"] = 15] = "TAB";
    dxKeyCodes[dxKeyCodes["Q"] = 16] = "Q";
    dxKeyCodes[dxKeyCodes["W"] = 17] = "W";
    dxKeyCodes[dxKeyCodes["E"] = 18] = "E";
    dxKeyCodes[dxKeyCodes["R"] = 19] = "R";
    dxKeyCodes[dxKeyCodes["T"] = 20] = "T";
    dxKeyCodes[dxKeyCodes["Y"] = 21] = "Y";
    dxKeyCodes[dxKeyCodes["U"] = 22] = "U";
    dxKeyCodes[dxKeyCodes["I"] = 23] = "I";
    dxKeyCodes[dxKeyCodes["O"] = 24] = "O";
    dxKeyCodes[dxKeyCodes["P"] = 25] = "P";
    dxKeyCodes[dxKeyCodes["["] = 26] = "[";
    dxKeyCodes[dxKeyCodes["]"] = 27] = "]";
    dxKeyCodes[dxKeyCodes["RETURN"] = 28] = "RETURN";
    dxKeyCodes[dxKeyCodes[" CONTROL"] = 29] = " CONTROL";
    dxKeyCodes[dxKeyCodes["A"] = 30] = "A";
    dxKeyCodes[dxKeyCodes["S"] = 31] = "S";
    dxKeyCodes[dxKeyCodes["D"] = 32] = "D";
    dxKeyCodes[dxKeyCodes["F"] = 33] = "F";
    dxKeyCodes[dxKeyCodes["G"] = 34] = "G";
    dxKeyCodes[dxKeyCodes["H"] = 35] = "H";
    dxKeyCodes[dxKeyCodes["J"] = 36] = "J";
    dxKeyCodes[dxKeyCodes["K"] = 37] = "K";
    dxKeyCodes[dxKeyCodes["L"] = 38] = "L";
    dxKeyCodes[dxKeyCodes[";"] = 39] = ";";
    dxKeyCodes[dxKeyCodes[" ' "] = 40] = " ' ";
    dxKeyCodes[dxKeyCodes["`"] = 41] = "`";
    dxKeyCodes[dxKeyCodes["SHIFT"] = 42] = "SHIFT";
    dxKeyCodes[dxKeyCodes["\\"] = 43] = "\\";
    dxKeyCodes[dxKeyCodes["Z"] = 44] = "Z";
    dxKeyCodes[dxKeyCodes["X"] = 45] = "X";
    dxKeyCodes[dxKeyCodes["C"] = 46] = "C";
    dxKeyCodes[dxKeyCodes["V"] = 47] = "V";
    dxKeyCodes[dxKeyCodes["B"] = 48] = "B";
    dxKeyCodes[dxKeyCodes["N"] = 49] = "N";
    dxKeyCodes[dxKeyCodes["M"] = 50] = "M";
    dxKeyCodes[dxKeyCodes[","] = 51] = ",";
    dxKeyCodes[dxKeyCodes["."] = 52] = ".";
    dxKeyCodes[dxKeyCodes["/"] = 53] = "/";
    dxKeyCodes[dxKeyCodes[" SHIFT"] = 54] = " SHIFT";
    dxKeyCodes[dxKeyCodes["*"] = 55] = "*";
    dxKeyCodes[dxKeyCodes[" ALT"] = 56] = " ALT";
    dxKeyCodes[dxKeyCodes["SPACE"] = 57] = "SPACE";
    dxKeyCodes[dxKeyCodes["CAPSLCK"] = 58] = "CAPSLCK";
    dxKeyCodes[dxKeyCodes["F1"] = 59] = "F1";
    dxKeyCodes[dxKeyCodes["F2"] = 60] = "F2";
    dxKeyCodes[dxKeyCodes["F3"] = 61] = "F3";
    dxKeyCodes[dxKeyCodes["F4"] = 62] = "F4";
    dxKeyCodes[dxKeyCodes["F5"] = 63] = "F5";
    dxKeyCodes[dxKeyCodes["F6"] = 64] = "F6";
    dxKeyCodes[dxKeyCodes["F7"] = 65] = "F7";
    dxKeyCodes[dxKeyCodes["F8"] = 66] = "F8";
    dxKeyCodes[dxKeyCodes["F9"] = 67] = "F9";
    dxKeyCodes[dxKeyCodes["F10"] = 68] = "F10";
    dxKeyCodes[dxKeyCodes["NUMLCK"] = 69] = "NUMLCK";
    dxKeyCodes[dxKeyCodes["SCRLCK"] = 70] = "SCRLCK";
    dxKeyCodes[dxKeyCodes["NUM7"] = 71] = "NUM7";
    dxKeyCodes[dxKeyCodes["NUM8"] = 72] = "NUM8";
    dxKeyCodes[dxKeyCodes["NUM9"] = 73] = "NUM9";
    dxKeyCodes[dxKeyCodes["NUM-"] = 74] = "NUM-";
    dxKeyCodes[dxKeyCodes["NUM4"] = 75] = "NUM4";
    dxKeyCodes[dxKeyCodes["NUM5"] = 76] = "NUM5";
    dxKeyCodes[dxKeyCodes["NUM6"] = 77] = "NUM6";
    dxKeyCodes[dxKeyCodes["NUM+"] = 78] = "NUM+";
    dxKeyCodes[dxKeyCodes["NUM1"] = 79] = "NUM1";
    dxKeyCodes[dxKeyCodes["NUM2"] = 80] = "NUM2";
    dxKeyCodes[dxKeyCodes["NUM3"] = 81] = "NUM3";
    dxKeyCodes[dxKeyCodes["NUM0"] = 82] = "NUM0";
    dxKeyCodes[dxKeyCodes["NUM."] = 83] = "NUM.";
    dxKeyCodes[dxKeyCodes["OEM_102"] = 86] = "OEM_102";
    dxKeyCodes[dxKeyCodes["F11"] = 87] = "F11";
    dxKeyCodes[dxKeyCodes["F12"] = 88] = "F12";
    dxKeyCodes[dxKeyCodes["F13"] = 100] = "F13";
    dxKeyCodes[dxKeyCodes["F14"] = 101] = "F14";
    dxKeyCodes[dxKeyCodes["F15"] = 102] = "F15";
    dxKeyCodes[dxKeyCodes["KANA"] = 112] = "KANA";
    dxKeyCodes[dxKeyCodes["ABNT_C1"] = 115] = "ABNT_C1";
    dxKeyCodes[dxKeyCodes["CONVERT"] = 121] = "CONVERT";
    dxKeyCodes[dxKeyCodes["NOCONVERT"] = 123] = "NOCONVERT";
    dxKeyCodes[dxKeyCodes["YEN"] = 125] = "YEN";
    dxKeyCodes[dxKeyCodes["ABNT_C2"] = 126] = "ABNT_C2";
    dxKeyCodes[dxKeyCodes["NUM="] = 141] = "NUM=";
    dxKeyCodes[dxKeyCodes["PREVTRK"] = 144] = "PREVTRK";
    dxKeyCodes[dxKeyCodes["@"] = 145] = "@";
    dxKeyCodes[dxKeyCodes[":"] = 146] = ":";
    dxKeyCodes[dxKeyCodes["_"] = 147] = "_";
    dxKeyCodes[dxKeyCodes["KANJI"] = 148] = "KANJI";
    dxKeyCodes[dxKeyCodes["STOP"] = 149] = "STOP";
    dxKeyCodes[dxKeyCodes["AX"] = 150] = "AX";
    dxKeyCodes[dxKeyCodes["UNLABELED"] = 151] = "UNLABELED";
    dxKeyCodes[dxKeyCodes["NEXTTRK"] = 153] = "NEXTTRK";
    dxKeyCodes[dxKeyCodes["NUMENTER"] = 156] = "NUMENTER";
    dxKeyCodes[dxKeyCodes["CONTROL"] = 157] = "CONTROL";
    dxKeyCodes[dxKeyCodes["MUTE"] = 160] = "MUTE";
    dxKeyCodes[dxKeyCodes["CALC"] = 161] = "CALC";
    dxKeyCodes[dxKeyCodes["PLAYE"] = 162] = "PLAYE";
    dxKeyCodes[dxKeyCodes[" STOP"] = 164] = " STOP";
    dxKeyCodes[dxKeyCodes["VOLDN"] = 174] = "VOLDN";
    dxKeyCodes[dxKeyCodes["VOLUP"] = 176] = "VOLUP";
    dxKeyCodes[dxKeyCodes["HOME"] = 178] = "HOME";
    dxKeyCodes[dxKeyCodes["NUM,"] = 179] = "NUM,";
    dxKeyCodes[dxKeyCodes["NUM/"] = 181] = "NUM/";
    dxKeyCodes[dxKeyCodes["SYSRQ"] = 183] = "SYSRQ";
    dxKeyCodes[dxKeyCodes["RALT"] = 184] = "RALT";
    dxKeyCodes[dxKeyCodes["PAUSE"] = 197] = "PAUSE";
    dxKeyCodes[dxKeyCodes["HOME "] = 199] = "HOME ";
    dxKeyCodes[dxKeyCodes["UP"] = 200] = "UP";
    dxKeyCodes[dxKeyCodes["PAGEUP"] = 201] = "PAGEUP";
    dxKeyCodes[dxKeyCodes["LEFT"] = 203] = "LEFT";
    dxKeyCodes[dxKeyCodes["RIGHT"] = 205] = "RIGHT";
    dxKeyCodes[dxKeyCodes["END"] = 207] = "END";
    dxKeyCodes[dxKeyCodes["DOWN"] = 208] = "DOWN";
    dxKeyCodes[dxKeyCodes["PAGEDN"] = 209] = "PAGEDN";
    dxKeyCodes[dxKeyCodes["INSERT"] = 210] = "INSERT";
    dxKeyCodes[dxKeyCodes["DELETE"] = 211] = "DELETE";
    dxKeyCodes[dxKeyCodes["LWIN"] = 219] = "LWIN";
    dxKeyCodes[dxKeyCodes["RWIN"] = 220] = "RWIN";
    dxKeyCodes[dxKeyCodes["APPS"] = 221] = "APPS";
    dxKeyCodes[dxKeyCodes["POWER"] = 222] = "POWER";
    dxKeyCodes[dxKeyCodes["SLEEP"] = 223] = "SLEEP";
    dxKeyCodes[dxKeyCodes["WAKE"] = 227] = "WAKE";
    dxKeyCodes[dxKeyCodes["SEARCH"] = 229] = "SEARCH";
    dxKeyCodes[dxKeyCodes["WEBFAV"] = 230] = "WEBFAV";
    dxKeyCodes[dxKeyCodes["REFRESH"] = 231] = "REFRESH";
    dxKeyCodes[dxKeyCodes["WEBSTOP"] = 232] = "WEBSTOP";
    dxKeyCodes[dxKeyCodes["WEBFWD"] = 233] = "WEBFWD";
    dxKeyCodes[dxKeyCodes["WEBBCK"] = 234] = "WEBBCK";
    dxKeyCodes[dxKeyCodes["MYCMPTR"] = 235] = "MYCMPTR";
    dxKeyCodes[dxKeyCodes["MAIL"] = 236] = "MAIL";
    dxKeyCodes[dxKeyCodes["MEDIASLCT"] = 237] = "MEDIASLCT";
})(dxKeyCodes || (dxKeyCodes = {}));
exports.default = dxKeyCodes;