"use strict";
/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 */

Object.defineProperty(exports, "__esModule", { value: true });
var winKeyCodes;
(function (winKeyCodes) {
    winKeyCodes[winKeyCodes["KEY_Backspace"] = 8] = "KEY_Backspace";
    winKeyCodes[winKeyCodes["KEY_Tab"] = 9] = "KEY_Tab";
    winKeyCodes[winKeyCodes["KEY_Enter"] = 13] = "KEY_Enter";
    winKeyCodes[winKeyCodes["KEY_Shift"] = 16] = "KEY_Shift";
    winKeyCodes[winKeyCodes["KEY_Ctrl"] = 17] = "KEY_Ctrl";
    winKeyCodes[winKeyCodes["KEY_Alt"] = 18] = "KEY_Alt";
    winKeyCodes[winKeyCodes["KEY_PauseBreak"] = 19] = "KEY_PauseBreak";
    winKeyCodes[winKeyCodes["KEY_CapsLock"] = 20] = "KEY_CapsLock";
    winKeyCodes[winKeyCodes["KEY_Escape"] = 27] = "KEY_Escape";
    winKeyCodes[winKeyCodes["KEY_Spacebar"] = 32] = "KEY_Spacebar";
    winKeyCodes[winKeyCodes["KEY_PageUp"] = 33] = "KEY_PageUp";
    winKeyCodes[winKeyCodes["KEY_PageDown"] = 34] = "KEY_PageDown";
    winKeyCodes[winKeyCodes["KEY_End"] = 35] = "KEY_End";
    winKeyCodes[winKeyCodes["KEY_Home"] = 36] = "KEY_Home";
    winKeyCodes[winKeyCodes["KEY_LeftArrow"] = 37] = "KEY_LeftArrow";
    winKeyCodes[winKeyCodes["KEY_UpArrow"] = 38] = "KEY_UpArrow";
    winKeyCodes[winKeyCodes["KEY_RightArrow"] = 39] = "KEY_RightArrow";
    winKeyCodes[winKeyCodes["KEY_DownArrow"] = 40] = "KEY_DownArrow";
    winKeyCodes[winKeyCodes["KEY_PrintScrn"] = 44] = "KEY_PrintScrn";
    winKeyCodes[winKeyCodes["KEY_Insert"] = 45] = "KEY_Insert";
    winKeyCodes[winKeyCodes["KEY_Delete"] = 46] = "KEY_Delete";
    winKeyCodes[winKeyCodes["KEY_Zero"] = 48] = "KEY_Zero";
    winKeyCodes[winKeyCodes["KEY_One"] = 49] = "KEY_One";
    winKeyCodes[winKeyCodes["KEY_Two"] = 50] = "KEY_Two";
    winKeyCodes[winKeyCodes["KEY_Three"] = 51] = "KEY_Three";
    winKeyCodes[winKeyCodes["KEY_Four"] = 52] = "KEY_Four";
    winKeyCodes[winKeyCodes["KEY_Five"] = 53] = "KEY_Five";
    winKeyCodes[winKeyCodes["KEY_Six"] = 54] = "KEY_Six";
    winKeyCodes[winKeyCodes["KEY_Seven"] = 55] = "KEY_Seven";
    winKeyCodes[winKeyCodes["KEY_Eight"] = 56] = "KEY_Eight";
    winKeyCodes[winKeyCodes["KEY_Nine"] = 57] = "KEY_Nine";
    winKeyCodes[winKeyCodes["KEY_a"] = 65] = "KEY_a";
    winKeyCodes[winKeyCodes["KEY_b"] = 66] = "KEY_b";
    winKeyCodes[winKeyCodes["KEY_c"] = 67] = "KEY_c";
    winKeyCodes[winKeyCodes["KEY_d"] = 68] = "KEY_d";
    winKeyCodes[winKeyCodes["KEY_e"] = 69] = "KEY_e";
    winKeyCodes[winKeyCodes["KEY_f"] = 70] = "KEY_f";
    winKeyCodes[winKeyCodes["KEY_g"] = 71] = "KEY_g";
    winKeyCodes[winKeyCodes["KEY_h"] = 72] = "KEY_h";
    winKeyCodes[winKeyCodes["KEY_i"] = 73] = "KEY_i";
    winKeyCodes[winKeyCodes["KEY_j"] = 74] = "KEY_j";
    winKeyCodes[winKeyCodes["KEY_k"] = 75] = "KEY_k";
    winKeyCodes[winKeyCodes["KEY_l"] = 76] = "KEY_l";
    winKeyCodes[winKeyCodes["KEY_m"] = 77] = "KEY_m";
    winKeyCodes[winKeyCodes["KEY_n"] = 78] = "KEY_n";
    winKeyCodes[winKeyCodes["KEY_o"] = 79] = "KEY_o";
    winKeyCodes[winKeyCodes["KEY_p"] = 80] = "KEY_p";
    winKeyCodes[winKeyCodes["KEY_q"] = 81] = "KEY_q";
    winKeyCodes[winKeyCodes["KEY_r"] = 82] = "KEY_r";
    winKeyCodes[winKeyCodes["KEY_s"] = 83] = "KEY_s";
    winKeyCodes[winKeyCodes["KEY_t"] = 84] = "KEY_t";
    winKeyCodes[winKeyCodes["KEY_u"] = 85] = "KEY_u";
    winKeyCodes[winKeyCodes["KEY_v"] = 86] = "KEY_v";
    winKeyCodes[winKeyCodes["KEY_w"] = 87] = "KEY_w";
    winKeyCodes[winKeyCodes["KEY_x"] = 88] = "KEY_x";
    winKeyCodes[winKeyCodes["KEY_y"] = 89] = "KEY_y";
    winKeyCodes[winKeyCodes["KEY_z"] = 90] = "KEY_z";
    winKeyCodes[winKeyCodes["KEY_LeftWindowKey"] = 91] = "KEY_LeftWindowKey";
    winKeyCodes[winKeyCodes["KEY_RightWindowKey"] = 92] = "KEY_RightWindowKey";
    winKeyCodes[winKeyCodes["KEY_SelectKey"] = 93] = "KEY_SelectKey";
    winKeyCodes[winKeyCodes["KEY_Numpad0"] = 96] = "KEY_Numpad0";
    winKeyCodes[winKeyCodes["KEY_Numpad1"] = 97] = "KEY_Numpad1";
    winKeyCodes[winKeyCodes["KEY_Numpad2"] = 98] = "KEY_Numpad2";
    winKeyCodes[winKeyCodes["KEY_Numpad3"] = 99] = "KEY_Numpad3";
    winKeyCodes[winKeyCodes["KEY_Numpad4"] = 100] = "KEY_Numpad4";
    winKeyCodes[winKeyCodes["KEY_Numpad5"] = 101] = "KEY_Numpad5";
    winKeyCodes[winKeyCodes["KEY_Numpad6"] = 102] = "KEY_Numpad6";
    winKeyCodes[winKeyCodes["KEY_Numpad7"] = 103] = "KEY_Numpad7";
    winKeyCodes[winKeyCodes["KEY_Numpad8"] = 104] = "KEY_Numpad8";
    winKeyCodes[winKeyCodes["KEY_Numpad9"] = 105] = "KEY_Numpad9";
    winKeyCodes[winKeyCodes["KEY_Multiply"] = 106] = "KEY_Multiply";
    winKeyCodes[winKeyCodes["KEY_NumpadPlus"] = 107] = "KEY_NumpadPlus";
    winKeyCodes[winKeyCodes["KEY_NumpadMinus"] = 109] = "KEY_NumpadMinus";
    winKeyCodes[winKeyCodes["KEY_DecimalPoint"] = 110] = "KEY_DecimalPoint";
    winKeyCodes[winKeyCodes["KEY_Divide"] = 111] = "KEY_Divide";
    winKeyCodes[winKeyCodes["KEY_F1"] = 112] = "KEY_F1";
    winKeyCodes[winKeyCodes["KEY_F2"] = 113] = "KEY_F2";
    winKeyCodes[winKeyCodes["KEY_F3"] = 114] = "KEY_F3";
    winKeyCodes[winKeyCodes["KEY_F4"] = 115] = "KEY_F4";
    winKeyCodes[winKeyCodes["KEY_F5"] = 116] = "KEY_F5";
    winKeyCodes[winKeyCodes["KEY_F6"] = 117] = "KEY_F6";
    winKeyCodes[winKeyCodes["KEY_F7"] = 118] = "KEY_F7";
    winKeyCodes[winKeyCodes["KEY_F8"] = 119] = "KEY_F8";
    winKeyCodes[winKeyCodes["KEY_F9"] = 120] = "KEY_F9";
    winKeyCodes[winKeyCodes["KEY_F10"] = 121] = "KEY_F10";
    winKeyCodes[winKeyCodes["KEY_F11"] = 122] = "KEY_F11";
    winKeyCodes[winKeyCodes["KEY_F12"] = 123] = "KEY_F12";
    winKeyCodes[winKeyCodes["KEY_NumLock"] = 144] = "KEY_NumLock";
    winKeyCodes[winKeyCodes["KEY_ScrollLock"] = 145] = "KEY_ScrollLock";
    winKeyCodes[winKeyCodes["KEY_Semicolon"] = 186] = "KEY_Semicolon";
    winKeyCodes[winKeyCodes["KEY_Equals"] = 187] = "KEY_Equals";
    winKeyCodes[winKeyCodes["KEY_Comma"] = 188] = "KEY_Comma";
    winKeyCodes[winKeyCodes["KEY_LessThan"] = 188] = "KEY_LessThan";
    winKeyCodes[winKeyCodes["KEY_Minus"] = 189] = "KEY_Minus";
    winKeyCodes[winKeyCodes["KEY_Period"] = 190] = "KEY_Period";
    winKeyCodes[winKeyCodes["KEY_GreaterThan"] = 190] = "KEY_GreaterThan";
    winKeyCodes[winKeyCodes["KEY_ForwardSlash"] = 191] = "KEY_ForwardSlash";
    winKeyCodes[winKeyCodes["KEY_QuestionMark"] = 191] = "KEY_QuestionMark";
    winKeyCodes[winKeyCodes["KEY_GraveAccent"] = 192] = "KEY_GraveAccent";
    winKeyCodes[winKeyCodes["KEY_Tilde"] = 192] = "KEY_Tilde";
    winKeyCodes[winKeyCodes["KEY_OpenCurlyBracket"] = 219] = "KEY_OpenCurlyBracket";
    winKeyCodes[winKeyCodes["KEY_OpenSquareBracket"] = 219] = "KEY_OpenSquareBracket";
    winKeyCodes[winKeyCodes["KEY_BackSlash"] = 220] = "KEY_BackSlash";
    winKeyCodes[winKeyCodes["KEY_VerticalPipe"] = 220] = "KEY_VerticalPipe";
    winKeyCodes[winKeyCodes["KEY_CloseCurlyBracket"] = 221] = "KEY_CloseCurlyBracket";
    winKeyCodes[winKeyCodes["KEY_CloseSquareBracket"] = 221] = "KEY_CloseSquareBracket";
    winKeyCodes[winKeyCodes["KEY_Quote"] = 222] = "KEY_Quote";
    winKeyCodes[winKeyCodes["KEY_CommandFF"] = 224] = "KEY_CommandFF";
})(winKeyCodes || (winKeyCodes = {}));
exports.default = winKeyCodes;