"use strict";
/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 */

Object.defineProperty(exports, "__esModule", { value: true });
var vkKeyCodes;
(function (vkKeyCodes) {
    vkKeyCodes[vkKeyCodes["VK_LBUTTON"] = 1] = "VK_LBUTTON";
    vkKeyCodes[vkKeyCodes["VK_RBUTTON"] = 2] = "VK_RBUTTON";
    vkKeyCodes[vkKeyCodes["VK_CANCEL"] = 3] = "VK_CANCEL";
    vkKeyCodes[vkKeyCodes["VK_MBUTTON"] = 4] = "VK_MBUTTON";
    vkKeyCodes[vkKeyCodes["VK_XBUTTON1"] = 5] = "VK_XBUTTON1";
    vkKeyCodes[vkKeyCodes["VK_XBUTTON2"] = 6] = "VK_XBUTTON2";
    vkKeyCodes[vkKeyCodes["VK_BACK"] = 8] = "VK_BACK";
    vkKeyCodes[vkKeyCodes["VK_TAB"] = 9] = "VK_TAB";
    vkKeyCodes[vkKeyCodes["VK_CLEAR"] = 12] = "VK_CLEAR";
    vkKeyCodes[vkKeyCodes["VK_RETURN"] = 13] = "VK_RETURN";
    vkKeyCodes[vkKeyCodes["VK_SHIFT"] = 16] = "VK_SHIFT";
    vkKeyCodes[vkKeyCodes["VK_CONTROL"] = 17] = "VK_CONTROL";
    vkKeyCodes[vkKeyCodes["VK_MENU"] = 18] = "VK_MENU";
    vkKeyCodes[vkKeyCodes["VK_PAUSE"] = 19] = "VK_PAUSE";
    vkKeyCodes[vkKeyCodes["VK_CAPITAL"] = 20] = "VK_CAPITAL";
    vkKeyCodes[vkKeyCodes["VK_KANA"] = 21] = "VK_KANA";
    vkKeyCodes[vkKeyCodes["VK_HANGUEL"] = 21] = "VK_HANGUEL";
    vkKeyCodes[vkKeyCodes["VK_HANGUL"] = 21] = "VK_HANGUL";
    vkKeyCodes[vkKeyCodes["VK_JUNJA"] = 23] = "VK_JUNJA";
    vkKeyCodes[vkKeyCodes["VK_FINAL"] = 24] = "VK_FINAL";
    vkKeyCodes[vkKeyCodes["VK_HANJA"] = 25] = "VK_HANJA";
    vkKeyCodes[vkKeyCodes["VK_KANJI"] = 25] = "VK_KANJI";
    vkKeyCodes[vkKeyCodes["VK_ESCAPE"] = 27] = "VK_ESCAPE";
    vkKeyCodes[vkKeyCodes["VK_CONVERT"] = 28] = "VK_CONVERT";
    vkKeyCodes[vkKeyCodes["VK_NONCONVERT"] = 29] = "VK_NONCONVERT";
    vkKeyCodes[vkKeyCodes["VK_ACCEPT"] = 30] = "VK_ACCEPT";
    vkKeyCodes[vkKeyCodes["VK_MODECHANGE"] = 31] = "VK_MODECHANGE";
    vkKeyCodes[vkKeyCodes["VK_SPACE"] = 32] = "VK_SPACE";
    vkKeyCodes[vkKeyCodes["VK_PRIOR"] = 33] = "VK_PRIOR";
    vkKeyCodes[vkKeyCodes["VK_NEXT"] = 34] = "VK_NEXT";
    vkKeyCodes[vkKeyCodes["VK_END"] = 35] = "VK_END";
    vkKeyCodes[vkKeyCodes["VK_HOME"] = 36] = "VK_HOME";
    vkKeyCodes[vkKeyCodes["VK_LEFT"] = 37] = "VK_LEFT";
    vkKeyCodes[vkKeyCodes["VK_UP"] = 38] = "VK_UP";
    vkKeyCodes[vkKeyCodes["VK_RIGHT"] = 39] = "VK_RIGHT";
    vkKeyCodes[vkKeyCodes["VK_DOWN"] = 40] = "VK_DOWN";
    vkKeyCodes[vkKeyCodes["VK_SELECT"] = 41] = "VK_SELECT";
    vkKeyCodes[vkKeyCodes["VK_PRINT"] = 42] = "VK_PRINT";
    vkKeyCodes[vkKeyCodes["VK_EXECUTE"] = 43] = "VK_EXECUTE";
    vkKeyCodes[vkKeyCodes["VK_SNAPSHOT"] = 44] = "VK_SNAPSHOT";
    vkKeyCodes[vkKeyCodes["VK_INSERT"] = 45] = "VK_INSERT";
    vkKeyCodes[vkKeyCodes["VK_DELETE"] = 46] = "VK_DELETE";
    vkKeyCodes[vkKeyCodes["VK_HELP"] = 47] = "VK_HELP";
    vkKeyCodes[vkKeyCodes["VK_0"] = 48] = "VK_0";
    vkKeyCodes[vkKeyCodes["VK_1"] = 49] = "VK_1";
    vkKeyCodes[vkKeyCodes["VK_2"] = 50] = "VK_2";
    vkKeyCodes[vkKeyCodes["VK_3"] = 51] = "VK_3";
    vkKeyCodes[vkKeyCodes["VK_4"] = 52] = "VK_4";
    vkKeyCodes[vkKeyCodes["VK_5"] = 53] = "VK_5";
    vkKeyCodes[vkKeyCodes["VK_6"] = 54] = "VK_6";
    vkKeyCodes[vkKeyCodes["VK_7"] = 55] = "VK_7";
    vkKeyCodes[vkKeyCodes["VK_8"] = 56] = "VK_8";
    vkKeyCodes[vkKeyCodes["VK_9"] = 57] = "VK_9";
    vkKeyCodes[vkKeyCodes["VK_A"] = 65] = "VK_A";
    vkKeyCodes[vkKeyCodes["VK_B"] = 66] = "VK_B";
    vkKeyCodes[vkKeyCodes["VK_C"] = 67] = "VK_C";
    vkKeyCodes[vkKeyCodes["VK_D"] = 68] = "VK_D";
    vkKeyCodes[vkKeyCodes["VK_E"] = 69] = "VK_E";
    vkKeyCodes[vkKeyCodes["VK_F"] = 70] = "VK_F";
    vkKeyCodes[vkKeyCodes["VK_G"] = 71] = "VK_G";
    vkKeyCodes[vkKeyCodes["VK_H"] = 72] = "VK_H";
    vkKeyCodes[vkKeyCodes["VK_I"] = 73] = "VK_I";
    vkKeyCodes[vkKeyCodes["VK_J"] = 74] = "VK_J";
    vkKeyCodes[vkKeyCodes["VK_K"] = 75] = "VK_K";
    vkKeyCodes[vkKeyCodes["VK_L"] = 76] = "VK_L";
    vkKeyCodes[vkKeyCodes["VK_M"] = 77] = "VK_M";
    vkKeyCodes[vkKeyCodes["VK_N"] = 78] = "VK_N";
    vkKeyCodes[vkKeyCodes["VK_O"] = 79] = "VK_O";
    vkKeyCodes[vkKeyCodes["VK_P"] = 80] = "VK_P";
    vkKeyCodes[vkKeyCodes["VK_Q"] = 81] = "VK_Q";
    vkKeyCodes[vkKeyCodes["VK_R"] = 82] = "VK_R";
    vkKeyCodes[vkKeyCodes["VK_S"] = 83] = "VK_S";
    vkKeyCodes[vkKeyCodes["VK_T"] = 84] = "VK_T";
    vkKeyCodes[vkKeyCodes["VK_U"] = 85] = "VK_U";
    vkKeyCodes[vkKeyCodes["VK_V"] = 86] = "VK_V";
    vkKeyCodes[vkKeyCodes["VK_W"] = 87] = "VK_W";
    vkKeyCodes[vkKeyCodes["VK_X"] = 88] = "VK_X";
    vkKeyCodes[vkKeyCodes["VK_Y"] = 89] = "VK_Y";
    vkKeyCodes[vkKeyCodes["VK_Z"] = 90] = "VK_Z";
    vkKeyCodes[vkKeyCodes["VK_LWIN"] = 91] = "VK_LWIN";
    vkKeyCodes[vkKeyCodes["VK_RWIN"] = 92] = "VK_RWIN";
    vkKeyCodes[vkKeyCodes["VK_APPS"] = 93] = "VK_APPS";
    vkKeyCodes[vkKeyCodes["VK_SLEEP"] = 95] = "VK_SLEEP";
    vkKeyCodes[vkKeyCodes["VK_NUMPAD0"] = 96] = "VK_NUMPAD0";
    vkKeyCodes[vkKeyCodes["VK_NUMPAD1"] = 97] = "VK_NUMPAD1";
    vkKeyCodes[vkKeyCodes["VK_NUMPAD2"] = 98] = "VK_NUMPAD2";
    vkKeyCodes[vkKeyCodes["VK_NUMPAD3"] = 99] = "VK_NUMPAD3";
    vkKeyCodes[vkKeyCodes["VK_NUMPAD4"] = 100] = "VK_NUMPAD4";
    vkKeyCodes[vkKeyCodes["VK_NUMPAD5"] = 101] = "VK_NUMPAD5";
    vkKeyCodes[vkKeyCodes["VK_NUMPAD6"] = 102] = "VK_NUMPAD6";
    vkKeyCodes[vkKeyCodes["VK_NUMPAD7"] = 103] = "VK_NUMPAD7";
    vkKeyCodes[vkKeyCodes["VK_NUMPAD8"] = 104] = "VK_NUMPAD8";
    vkKeyCodes[vkKeyCodes["VK_NUMPAD9"] = 105] = "VK_NUMPAD9";
    vkKeyCodes[vkKeyCodes["VK_MULTIPLY"] = 106] = "VK_MULTIPLY";
    vkKeyCodes[vkKeyCodes["VK_ADD"] = 107] = "VK_ADD";
    vkKeyCodes[vkKeyCodes["VK_SEPARATOR"] = 108] = "VK_SEPARATOR";
    vkKeyCodes[vkKeyCodes["VK_SUBTRACT"] = 109] = "VK_SUBTRACT";
    vkKeyCodes[vkKeyCodes["VK_DECIMAL"] = 110] = "VK_DECIMAL";
    vkKeyCodes[vkKeyCodes["VK_DIVIDE"] = 111] = "VK_DIVIDE";
    vkKeyCodes[vkKeyCodes["VK_F1"] = 112] = "VK_F1";
    vkKeyCodes[vkKeyCodes["VK_F2"] = 113] = "VK_F2";
    vkKeyCodes[vkKeyCodes["VK_F3"] = 114] = "VK_F3";
    vkKeyCodes[vkKeyCodes["VK_F4"] = 115] = "VK_F4";
    vkKeyCodes[vkKeyCodes["VK_F5"] = 116] = "VK_F5";
    vkKeyCodes[vkKeyCodes["VK_F6"] = 117] = "VK_F6";
    vkKeyCodes[vkKeyCodes["VK_F7"] = 118] = "VK_F7";
    vkKeyCodes[vkKeyCodes["VK_F8"] = 119] = "VK_F8";
    vkKeyCodes[vkKeyCodes["VK_F9"] = 120] = "VK_F9";
    vkKeyCodes[vkKeyCodes["VK_F10"] = 121] = "VK_F10";
    vkKeyCodes[vkKeyCodes["VK_F11"] = 122] = "VK_F11";
    vkKeyCodes[vkKeyCodes["VK_F12"] = 123] = "VK_F12";
    vkKeyCodes[vkKeyCodes["VK_F13"] = 124] = "VK_F13";
    vkKeyCodes[vkKeyCodes["VK_F14"] = 125] = "VK_F14";
    vkKeyCodes[vkKeyCodes["VK_F15"] = 126] = "VK_F15";
    vkKeyCodes[vkKeyCodes["VK_F16"] = 127] = "VK_F16";
    vkKeyCodes[vkKeyCodes["VK_F17"] = 128] = "VK_F17";
    vkKeyCodes[vkKeyCodes["VK_F18"] = 129] = "VK_F18";
    vkKeyCodes[vkKeyCodes["VK_F19"] = 130] = "VK_F19";
    vkKeyCodes[vkKeyCodes["VK_F20"] = 131] = "VK_F20";
    vkKeyCodes[vkKeyCodes["VK_F21"] = 132] = "VK_F21";
    vkKeyCodes[vkKeyCodes["VK_F22"] = 133] = "VK_F22";
    vkKeyCodes[vkKeyCodes["VK_F23"] = 134] = "VK_F23";
    vkKeyCodes[vkKeyCodes["VK_F24"] = 135] = "VK_F24";
    vkKeyCodes[vkKeyCodes["VK_NUMLOCK"] = 144] = "VK_NUMLOCK";
    vkKeyCodes[vkKeyCodes["VK_SCROLL"] = 145] = "VK_SCROLL";
    vkKeyCodes[vkKeyCodes["VK_LSHIFT"] = 160] = "VK_LSHIFT";
    vkKeyCodes[vkKeyCodes["VK_RSHIFT"] = 161] = "VK_RSHIFT";
    vkKeyCodes[vkKeyCodes["VK_LCONTROL"] = 162] = "VK_LCONTROL";
    vkKeyCodes[vkKeyCodes["VK_RCONTROL"] = 163] = "VK_RCONTROL";
    vkKeyCodes[vkKeyCodes["VK_LMENU"] = 164] = "VK_LMENU";
    vkKeyCodes[vkKeyCodes["VK_RMENU"] = 165] = "VK_RMENU";
    vkKeyCodes[vkKeyCodes["VK_BROWSER_BACK"] = 166] = "VK_BROWSER_BACK";
    vkKeyCodes[vkKeyCodes["VK_BROWSER_FORWARD"] = 167] = "VK_BROWSER_FORWARD";
    vkKeyCodes[vkKeyCodes["VK_BROWSER_REFRESH"] = 168] = "VK_BROWSER_REFRESH";
    vkKeyCodes[vkKeyCodes["VK_BROWSER_STOP"] = 169] = "VK_BROWSER_STOP";
    vkKeyCodes[vkKeyCodes["VK_BROWSER_SEARCH"] = 170] = "VK_BROWSER_SEARCH";
    vkKeyCodes[vkKeyCodes["VK_BROWSER_FAVORITES"] = 171] = "VK_BROWSER_FAVORITES";
    vkKeyCodes[vkKeyCodes["VK_BROWSER_HOME"] = 172] = "VK_BROWSER_HOME";
    vkKeyCodes[vkKeyCodes["VK_VOLUME_MUTE"] = 173] = "VK_VOLUME_MUTE";
    vkKeyCodes[vkKeyCodes["VK_VOLUME_DOWN"] = 174] = "VK_VOLUME_DOWN";
    vkKeyCodes[vkKeyCodes["VK_VOLUME_UP"] = 175] = "VK_VOLUME_UP";
    vkKeyCodes[vkKeyCodes["VK_MEDIA_NEXT_TRACK"] = 176] = "VK_MEDIA_NEXT_TRACK";
    vkKeyCodes[vkKeyCodes["VK_MEDIA_PREV_TRACK"] = 177] = "VK_MEDIA_PREV_TRACK";
    vkKeyCodes[vkKeyCodes["VK_MEDIA_STOP"] = 178] = "VK_MEDIA_STOP";
    vkKeyCodes[vkKeyCodes["VK_MEDIA_PLAY_PAUSE"] = 179] = "VK_MEDIA_PLAY_PAUSE";
    vkKeyCodes[vkKeyCodes["VK_LAUNCH_MAIL"] = 180] = "VK_LAUNCH_MAIL";
    vkKeyCodes[vkKeyCodes["VK_LAUNCH_MEDIA_SELECT"] = 181] = "VK_LAUNCH_MEDIA_SELECT";
    vkKeyCodes[vkKeyCodes["VK_LAUNCH_APP1"] = 182] = "VK_LAUNCH_APP1";
    vkKeyCodes[vkKeyCodes["VK_LAUNCH_APP2"] = 183] = "VK_LAUNCH_APP2";
    vkKeyCodes[vkKeyCodes["VK_OEM_1"] = 186] = "VK_OEM_1";
    // For the US standard keyboard, the ',:' key
    vkKeyCodes[vkKeyCodes["VK_OEM_PLUS"] = 187] = "VK_OEM_PLUS";
    vkKeyCodes[vkKeyCodes["VK_OEM_COMMA"] = 188] = "VK_OEM_COMMA";
    vkKeyCodes[vkKeyCodes["VK_OEM_MINUS"] = 189] = "VK_OEM_MINUS";
    vkKeyCodes[vkKeyCodes["VK_OEM_PERIOD"] = 190] = "VK_OEM_PERIOD";
    vkKeyCodes[vkKeyCodes["VK_OEM_2"] = 191] = "VK_OEM_2";
    // For the US standard keyboard, the '/?' key
    vkKeyCodes[vkKeyCodes["VK_OEM_3"] = 192] = "VK_OEM_3";
    // For the US standard keyboard, the '`~' key
    vkKeyCodes[vkKeyCodes["VK_OEM_4"] = 219] = "VK_OEM_4";
    // For the US standard keyboard, the '[{' key
    vkKeyCodes[vkKeyCodes["VK_OEM_5"] = 220] = "VK_OEM_5";
    // For the US standard keyboard, the '\|' key
    vkKeyCodes[vkKeyCodes["VK_OEM_6"] = 221] = "VK_OEM_6";
    // For the US standard keyboard, the ']}' key
    vkKeyCodes[vkKeyCodes["VK_OEM_7"] = 222] = "VK_OEM_7";
    // For the US standard keyboard, the 'single-quote/double-quote' key
    vkKeyCodes[vkKeyCodes["VK_OEM_8"] = 223] = "VK_OEM_8";
    vkKeyCodes[vkKeyCodes["VK_OEM_102"] = 226] = "VK_OEM_102";
    vkKeyCodes[vkKeyCodes["VK_PROCESSKEY"] = 229] = "VK_PROCESSKEY";
    vkKeyCodes[vkKeyCodes["VK_PACKET"] = 231] = "VK_PACKET";
    // The VK_PACKET key is the low word of a 32-bit Virtual Key value used for non-keyboard input methods.
    // For more information, see Remark in KEYBDINPUT, SendInput, WM_KEYDOWN, and WM_KEYUP = ,
    vkKeyCodes[vkKeyCodes["VK_ATTN"] = 246] = "VK_ATTN";
    vkKeyCodes[vkKeyCodes["VK_CRSEL"] = 247] = "VK_CRSEL";
    vkKeyCodes[vkKeyCodes["VK_EXSEL"] = 248] = "VK_EXSEL";
    vkKeyCodes[vkKeyCodes["VK_EREOF"] = 249] = "VK_EREOF";
    vkKeyCodes[vkKeyCodes["VK_PLAY"] = 250] = "VK_PLAY";
    vkKeyCodes[vkKeyCodes["VK_ZOOM"] = 251] = "VK_ZOOM";
    vkKeyCodes[vkKeyCodes["VK_NONAME"] = 252] = "VK_NONAME";
    vkKeyCodes[vkKeyCodes["VK_PA1"] = 253] = "VK_PA1";
    vkKeyCodes[vkKeyCodes["VK_OEM_CLEAR"] = 254] = "VK_OEM_CLEAR";
})(vkKeyCodes || (vkKeyCodes = {}));
exports.default = vkKeyCodes;