export declare function changeMode(mode: number): void;
export declare function commit(): void;
export declare function undo(): void;
export declare function redo(): void;
export declare function rotateX(): void;
export declare function rotateY(): void;
export declare function rotateZ(): void;
export declare function flipX(): void;
export declare function flipY(): void;
export declare function flipZ(): void;
